### ISSUE TITLE
Demo app and jupyter complain about OpenSearch errors

### ISSUE THREAD

**Issue by stockholmux** [aryn-ai/quickstart#31]
When I try to get the demo app going, get the follow errors when I connect to `localhost:3000`
<img width="1279" alt="screenshot" src="https://github.com/aryn-ai/quickstart/assets/1152927/7e80592a-f16f-427a-aaab-96ad8b22c853">

If I dismiss the error, and try to interact with the demo, I get this error:
<img width="406" alt="screenshot" src="https://github.com/aryn-ai/quickstart/assets/1152927/64859e80-fd06-43af-bb2b-a1575e982c97">

I went and tried to run through the Jupyter notebook demo and got a similar issue once I tired to connect to OpenSearch.

On a whim, I changed the `OPENSEARCH_VERSION` to `0.2023.11.27` and `0.2023.11.21` with the same effect.

I'm running Docker on Linux (kernel v `5.15.0-76-generic`) with plenty of headroom in both CPU and memory.

**Comment by eric-anderson** [comment]
My first guess is that there is insufficient disk space for the image which makes opensearch unhappy. It needs at least 5% free disk space or it will throw errors; the images are large so it's easy to run low on disk space without realizing it.

Two things to try:
1) Reset and bring up opensearch by itself
  a) reset the configuration -- https://github.com/aryn-ai/quickstart#reset-the-configuration-entirely
      % docker compose down
      % docker compose run reset
  b) bring up opensearch
      % docker compose up opensearch
  c) wait for the success log message "Also linked to: /usr/share/opensearch/data/aryn_status/opensearch.log"
      or the error log message "opensearch to start did not happen within 300 seconds"
  d) if that works, ctrl-c and run docker compose up, it will probably all be working.
       if you get the error message, check with df for free disk space 

2) Send us the log files:
    % docker compose logs >compose.logs
    and then send us that either attached to this issue, or in the slack channel
    https://join.slack.com/t/sycamore-ulj8912/shared_invite/zt-23sv0yhgy-MywV5dkVQ~F98Aoejo48Jg

**Comment by stockholmux** [comment]
So, after much tinkering, I was able to get the demo running in my environment.  Thanks or your help!

The `reset` did get me further than previous tries although I don't think disk space was an issue as there were hundreds of gb free and subsequent runs haven't shown the original problem. Later, I had problems with the API being blocked in my particular setup and then I was out of OpenAI credit, both were nothing to do with the demo (although the error messages were not particularly helpful in figuring out the problem).
